import { z } from 'zod'

export const readFileSchema = z.object({
  path: z.string().describe('File path relative to the workspace root.'),
})

export const writeFileSchema = z.object({
  path: z.string().describe('File path relative to the workspace root.'),
  content: z.string().describe('Full file contents to write.'),
})

export const patchFileSchema = z.object({
  path: z.string().describe('Target file path relative to the workspace root.').optional(),
  patch: z.string().describe('Unified diff patch generated by git-style tools.'),
})

export const executeShellSchema = z.object({
  command: z.string().describe('Command to execute using bash -lc.'),
  background: z.boolean().optional().describe('Run the command as a background task. Defaults to false.'),
  timeoutMs: z.number().int().positive().optional().describe('Optional timeout in milliseconds.'),
})

export const searchFilesSchema = z.object({
  pattern: z.string().describe('Text or regex pattern to search for with ripgrep.'),
  path: z.string().optional().describe('Optional workspace-relative directory or file to search.'),
  glob: z.string().optional().describe('Optional ripgrep glob, for example "*.ts".'),
})

export const slashCommandSchema = z.object({
  name: z
    .string()
    .describe("Slash command to execute (with optional namespace). Example: 'context' or 'frontend/context'."),
  arguments: z
    .string()
    .describe('Arguments forwarded to the command; they will populate $ARGUMENTS and positional placeholders.')
    .optional(),
})

export const spawnAgentSchema = z.object({
  role: z.enum(['default', 'explorer', 'worker']).default('default'),
  prompt: z.string().describe('Prompt for the delegated agent.'),
  description: z.string().optional().describe('Short task description.'),
  background: z.boolean().optional().describe('Run the delegated agent in the background. Defaults to false.'),
})

export const runAgentsSchema = z.object({
  agents: z
    .array(
      z.object({
        role: z.enum(['default', 'explorer', 'worker']).default('default'),
        prompt: z.string().describe('Prompt for the delegated agent.'),
        description: z.string().optional().describe('Short task description.'),
      }),
    )
    .min(1)
    .max(20)
    .describe('Delegated agents to run concurrently. Use this when every result is needed before continuing.'),
})

export const readTaskOutputSchema = z.object({
  taskId: z.string().describe('Task id to inspect.'),
})

export const listTasksSchema = z.object({})

export const getTaskStatusSchema = z.object({
  taskId: z.string().describe('Task id to inspect.'),
})

export const waitForTasksSchema = z.object({
  taskIds: z.array(z.string()).min(1).max(50).describe('Task ids to wait for.'),
  timeoutMs: z.number().int().positive().optional().describe('Optional timeout in milliseconds. Omit for no timeout.'),
})

export const cancelTaskSchema = z.object({
  taskId: z.string().describe('Task id to cancel.'),
})

export const writeMemorySchema = z.object({
  type: z.enum(['user', 'feedback', 'project', 'reference']).default('feedback'),
  name: z.string().describe('Memory name.'),
  description: z.string().describe('One-line memory description.'),
  content: z.string().describe('Full memory content to store.'),
})

export const activateSkillSchema = z.object({
  name: z
    .string()
    .describe('Exact name of the skill to activate. Must match one of the skills listed in the tool description.'),
})
