import { mkdir, unlink } from 'node:fs/promises'
import path from 'node:path'
import { z } from 'zod'

import { MAX_FILE_CHARS, MAX_SHELL_OUTPUT, workspaceRoot } from '../config'
import { readTaskOutput } from '../tasks/task-output'
import type { TaskRecord } from '../tasks/task-types'
import { createUnifiedDiff } from '../lib/change-diff'
import { applyUnifiedDiff, sanitizePatchTargets, splitUnifiedDiffByFile } from '../lib/diff'
import { truncate } from '../lib/text'
import { formatToolSummary, summarizeToolCompletion } from '../lib/toolSummaries'
import { relativeWorkspacePath, resolveWorkspacePath } from '../lib/workspace'
import {
  buildSlashCommandToolDescription,
  executeSlashCommand,
  loadSlashCommands,
  type SlashCommandExecution,
} from '../lib/slashCommands'
import {
  activateSkill,
  buildActivateSkillToolDescription,
  loadSkills,
} from '../lib/skills'
import type { ToolDefinition } from './tool-types'
import { discoverMCPTools, mcpManagementTools } from './mcp'
import { enterPlanModeTool, exitPlanModeTool } from './plan-mode'
import { askUserQuestionTool } from './ask-user-question'

const MAX_AGENT_BATCH_INLINE_OUTPUT_CHARS = 12_000

const readFileSchema = z.object({
  path: z.string().describe('File path relative to the workspace root.'),
})

const writeFileSchema = z.object({
  path: z.string().describe('File path relative to the workspace root.'),
  content: z.string().describe('Full file contents to write.'),
})

const patchFileSchema = z.object({
  path: z.string().describe('Target file path relative to the workspace root.').optional(),
  patch: z.string().describe('Unified diff patch generated by git-style tools.'),
})

const executeShellSchema = z.object({
  command: z.string().describe('Command to execute using bash -lc.'),
  timeoutMs: z.number().int().positive().optional().describe('Optional timeout in milliseconds.'),
})

const searchFilesSchema = z.object({
  pattern: z.string().describe('Text or regex pattern to search for with ripgrep.'),
  path: z.string().optional().describe('Optional workspace-relative directory or file to search.'),
  glob: z.string().optional().describe('Optional ripgrep glob, for example "*.ts".'),
})

const slashCommandSchema = z.object({
  name: z
    .string()
    .describe("Slash command to execute (with optional namespace). Example: 'context' or 'frontend/context'."),
  arguments: z
    .string()
    .describe('Arguments forwarded to the command; they will populate $ARGUMENTS and positional placeholders.')
    .optional(),
})

const spawnAgentSchema = z.object({
  role: z.enum(['default', 'explorer', 'worker']).default('default'),
  prompt: z.string().describe('Prompt for the delegated agent.'),
  description: z.string().optional().describe('Short task description.'),
  background: z.boolean().optional().describe('Run the delegated agent in the background. Defaults to false.'),
})

const runAgentsSchema = z.object({
  agents: z
    .array(
      z.object({
        role: z.enum(['default', 'explorer', 'worker']).default('default'),
        prompt: z.string().describe('Prompt for the delegated agent.'),
        description: z.string().optional().describe('Short task description.'),
      }),
    )
    .min(1)
    .max(20)
    .describe('Delegated agents to run concurrently. Use this when every result is needed before continuing.'),
})

const readTaskOutputSchema = z.object({
  taskId: z.string().describe('Task id to inspect.'),
})

const listTasksSchema = z.object({})

const getTaskStatusSchema = z.object({
  taskId: z.string().describe('Task id to inspect.'),
})

const waitForTasksSchema = z.object({
  taskIds: z.array(z.string()).min(1).max(50).describe('Task ids to wait for.'),
  timeoutMs: z.number().int().positive().optional().describe('Optional timeout in milliseconds. Omit for no timeout.'),
})

const cancelTaskSchema = z.object({
  taskId: z.string().describe('Task id to cancel.'),
})

const writeMemorySchema = z.object({
  type: z.enum(['user', 'feedback', 'project', 'reference']).default('feedback'),
  name: z.string().describe('Memory name.'),
  description: z.string().describe('One-line memory description.'),
  content: z.string().describe('Full memory content to store.'),
})

const activateSkillSchema = z.object({
  name: z
    .string()
    .describe('Exact name of the skill to activate. Must match one of the skills listed in the tool description.'),
})

function formatFileChangeResult(message: string, diff: string): string {
  return diff.trim() ? `${message}\n\nDiff:\n\`\`\`diff\n${diff.trimEnd()}\n\`\`\`` : message
}

function ensureNonEmptyString(value: unknown, label: string): string {
  if (typeof value !== 'string') {
    throw new Error(`Parameter "${label}" must be a string.`)
  }

  const trimmed = value.trim()
  if (!trimmed) {
    throw new Error(`Parameter "${label}" must not be empty.`)
  }

  return trimmed
}

async function runShell(command: string): Promise<{ stdout: string; stderr: string; exitCode: number }> {
  const process = Bun.spawn(['bash', '-lc', command], {
    cwd: workspaceRoot,
    stdout: 'pipe',
    stderr: 'pipe',
  })

  const stdoutPromise = process.stdout ? new Response(process.stdout).text() : Promise.resolve('')
  const stderrPromise = process.stderr ? new Response(process.stderr).text() : Promise.resolve('')
  const [stdout, stderr, exitCode] = await Promise.all([stdoutPromise, stderrPromise, process.exited])
  return { stdout, stderr, exitCode }
}

async function runRipgrepSearch(input: { pattern: string; path?: string; glob?: string }): Promise<string> {
  const pattern = ensureNonEmptyString(input.pattern, 'pattern')
  const searchPath = input.path?.trim() ? relativeWorkspacePath(resolveWorkspacePath(input.path)) : '.'
  const args = ['--line-number', '--no-heading', '--color=never']
  if (input.glob?.trim()) {
    args.push('--glob', input.glob.trim())
  }
  args.push('--', pattern, searchPath)

  const process = Bun.spawn(['rg', ...args], {
    cwd: workspaceRoot,
    stdout: 'pipe',
    stderr: 'pipe',
  })

  const stdoutPromise = process.stdout ? new Response(process.stdout).text() : Promise.resolve('')
  const stderrPromise = process.stderr ? new Response(process.stderr).text() : Promise.resolve('')
  const [stdout, stderr, exitCode] = await Promise.all([stdoutPromise, stderrPromise, process.exited])
  if (exitCode === 0) {
    return truncate(stdout, MAX_SHELL_OUTPUT)
  }
  if (exitCode === 1) {
    return 'No matches found.'
  }
  throw new Error(stderr.trim() || `rg exited with code ${exitCode}`)
}

function summarizeTask(task: TaskRecord): Record<string, unknown> {
  return {
    id: task.id,
    kind: task.kind,
    title: task.title,
    status: task.status,
    background: task.background,
    createdAt: task.createdAt,
    startedAt: task.startedAt,
    finishedAt: task.finishedAt,
    progressSummary: task.progressSummary,
    error: task.error,
    metadata: task.metadata,
  }
}

function formatAgentBatchResult(result: {
  tasks: Array<{ task: TaskRecord; output: string }>
}): string {
  const sections = result.tasks.map(({ task, output }, index) => {
    const header = [
      `## Agent ${index + 1}: ${task.title}`,
      `Task ID: ${task.id}`,
      `Status: ${task.status}`,
      task.outputPath ? `Full output: ${task.outputPath}` : null,
      task.error ? `Error: ${task.error}` : null,
    ]
      .filter(Boolean)
      .join('\n')
    const body = truncate(
      output.trim() || task.progressSummary || '(no output)',
      MAX_AGENT_BATCH_INLINE_OUTPUT_CHARS,
    )
    return `${header}\n\n${body}`
  })

  const failed = result.tasks.filter(({ task }) => task.status === 'failed' || task.status === 'cancelled')
  const summary =
    failed.length === 0
      ? `Ran ${result.tasks.length} delegated agent${result.tasks.length === 1 ? '' : 's'} concurrently.`
      : `Ran ${result.tasks.length} delegated agent${result.tasks.length === 1 ? '' : 's'} concurrently; ${failed.length} did not complete successfully.`

  return `${summary}\n\n${sections.join('\n\n---\n\n')}`
}

function formatShellResult(exitCode: number, stdout: string, stderr: string): string {
  const outputParts = [
    `exit_code: ${exitCode}`,
    stdout ? `stdout:\n${truncate(stdout, MAX_SHELL_OUTPUT)}` : 'stdout: <empty>',
    stderr ? `stderr:\n${truncate(stderr, MAX_SHELL_OUTPUT)}` : 'stderr: <empty>',
  ]
  return outputParts.join('\n\n')
}

function formatSlashCommandMessage(execution: SlashCommandExecution): string {
  const scopeLabel = execution.namespace ? `${execution.scope}:${execution.namespace}` : execution.scope
  const header: string[] = [`Command · ${execution.command}`, `Scope · ${scopeLabel}`]

  if (execution.arguments) {
    header.push(`Arguments · ${execution.arguments}`)
  }
  if (execution.allowedTools.length > 0) {
    header.push(`Allowed tools · ${execution.allowedTools.join(', ')}`)
  }
  if (execution.model) {
    header.push(`Preferred model · ${execution.model}`)
  }

  const headerBlock = header.join('\n')
  if (!execution.content) {
    return headerBlock
  }

  return `${headerBlock}\n\n${execution.content}`
}

export async function createBuiltInToolDefinitions(
  options: { includeSpawnAgent?: boolean; includeMCPTools?: boolean; discoverMCPServerTools?: boolean } = {},
): Promise<ToolDefinition<any, any>[]> {
  const cachedSlashCommands = await loadSlashCommands()
  const slashCommandDescription = buildSlashCommandToolDescription(cachedSlashCommands)
  const cachedSkills = await loadSkills()

  const readFileTool: ToolDefinition<typeof readFileSchema, string> = {
    id: 'readFile',
    displayName: 'Read File',
    description: 'Read a UTF-8 file from the workspace.',
    inputSchema: readFileSchema,
    summarize: (result, context) =>
      formatToolSummary(
        summarizeToolCompletion('readFile', context.input, result, { artifactPath: context.artifactPath }),
      ),
    execute: async ({ path: targetPath }) => {
      const normalizedPath = ensureNonEmptyString(targetPath, 'path')
      const resolvedPath = resolveWorkspacePath(normalizedPath)
      const file = Bun.file(resolvedPath)
      if (!(await file.exists())) {
        return `File not found: ${relativeWorkspacePath(resolvedPath)}`
      }
      const content = await file.text()
      return truncate(content, MAX_FILE_CHARS)
    },
  }

  const searchFilesTool: ToolDefinition<typeof searchFilesSchema, string> = {
    id: 'searchFiles',
    displayName: 'Search Files',
    description: 'Search workspace files with ripgrep. Read-only.',
    inputSchema: searchFilesSchema,
    summarize: (result, context) =>
      formatToolSummary(
        summarizeToolCompletion('searchFiles', context.input, result, { artifactPath: context.artifactPath }),
      ),
    execute: async (input) => {
      return runRipgrepSearch(input)
    },
  }

  const writeFileTool: ToolDefinition<typeof writeFileSchema, string> = {
    id: 'writeFile',
    displayName: 'Write File',
    description: 'Overwrite a file in the workspace with new content.',
    inputSchema: writeFileSchema,
    summarize: (result, context) =>
      formatToolSummary(
        summarizeToolCompletion('writeFile', context.input, result, { artifactPath: context.artifactPath }),
      ),
    execute: async ({ path: targetPath, content }) => {
      const normalizedPath = ensureNonEmptyString(targetPath, 'path')
      if (typeof content !== 'string') {
        throw new Error('Parameter "content" must be a string.')
      }

      const resolvedPath = resolveWorkspacePath(normalizedPath)
      const relativePath = relativeWorkspacePath(resolvedPath)
      const file = Bun.file(resolvedPath)
      const exists = await file.exists()
      const oldText = exists ? await file.text() : ''
      const diff = createUnifiedDiff({
        oldPath: exists ? relativePath : null,
        newPath: relativePath,
        oldText,
        newText: content,
      })

      await mkdir(path.dirname(resolvedPath), { recursive: true })
      const bytesWritten = await Bun.write(resolvedPath, content)
      return formatFileChangeResult(`Wrote ${bytesWritten} bytes to ${relativePath}.`, diff)
    },
    getPermissionRequest: ({ path: targetPath }) => ({
      subject: `Write file: ${targetPath}`,
      metadata: { path: targetPath },
    }),
  }

  const patchFileTool: ToolDefinition<typeof patchFileSchema, string> = {
    id: 'patchFile',
    displayName: 'Patch File',
    description: 'Apply a unified diff patch to a file.',
    inputSchema: patchFileSchema,
    summarize: (result, context) =>
      formatToolSummary(
        summarizeToolCompletion('patchFile', context.input, result, { artifactPath: context.artifactPath }),
      ),
    execute: async ({ path: targetPath, patch }) => {
      const normalizedPatch = ensureNonEmptyString(patch, 'patch')

      if (normalizedPatch.includes('*** Begin Patch')) {
        throw new Error('apply_patch formatted patches are not supported.')
      }

      const trimmedTarget = targetPath?.trim()
      const explicitTarget = trimmedTarget ? relativeWorkspacePath(resolveWorkspacePath(trimmedTarget)) : null
      const perFilePatches = splitUnifiedDiffByFile(normalizedPatch)

      if (perFilePatches.length === 0) {
        if (!explicitTarget) {
          throw new Error('Unable to determine patch target. Provide a path parameter.')
        }

        const resolvedPath = resolveWorkspacePath(explicitTarget)
        const relativePath = relativeWorkspacePath(resolvedPath)
        sanitizePatchTargets(normalizedPatch, relativePath)

        const file = Bun.file(resolvedPath)
        const exists = await file.exists()
        const baseText = exists ? await file.text() : ''
        const updated = applyUnifiedDiff(baseText, normalizedPatch)
        const isDeletion = /\+\+\+\s+\/dev\/null/.test(normalizedPatch)

        if (isDeletion) {
          if (!exists) {
            throw new Error(`Cannot delete non-existent file: ${relativePath}`)
          }
          await unlink(resolvedPath)
          return `Deleted ${relativePath} via patch.`
        }

        await mkdir(path.dirname(resolvedPath), { recursive: true })
        await Bun.write(resolvedPath, updated)

        return `${exists ? 'Updated' : 'Created'} ${relativePath} via patch.`
      }

      if (explicitTarget && perFilePatches.length > 1) {
        throw new Error('Patch modifies multiple files. Omit the path parameter to allow this.')
      }

      const results: string[] = []

      for (const filePatch of perFilePatches) {
        const { patchText, oldPath, newPath } = filePatch
        const resolvedOld = oldPath ? resolveWorkspacePath(oldPath) : null
        const resolvedNew = newPath ? resolveWorkspacePath(newPath) : null
        const relativeOld = resolvedOld ? relativeWorkspacePath(resolvedOld) : null
        const relativeNew = resolvedNew ? relativeWorkspacePath(resolvedNew) : null
        const allowedTargets = [relativeOld, relativeNew].filter((value): value is string => Boolean(value))

        if (explicitTarget && !allowedTargets.includes(explicitTarget)) {
          throw new Error(`Patch modifies ${allowedTargets.join(', ')} but expected ${explicitTarget}.`)
        }

        sanitizePatchTargets(patchText, allowedTargets)

        if (!resolvedNew) {
          if (!resolvedOld) {
            throw new Error('Patch missing target path for deletion.')
          }

          const file = Bun.file(resolvedOld)
          if (!(await file.exists())) {
            throw new Error(`Cannot delete non-existent file: ${relativeOld}`)
          }
          await unlink(resolvedOld)
          results.push(`Deleted ${relativeOld} via patch.`)
          continue
        }

        const basePath = resolvedOld ?? resolvedNew
        const baseFile = Bun.file(basePath)
        const baseExists = await baseFile.exists()

        if (!resolvedOld && baseExists) {
          throw new Error(`Cannot create ${relativeNew}: file already exists.`)
        }

        if (resolvedOld && !(await Bun.file(resolvedOld).exists())) {
          throw new Error(`Base file not found: ${relativeOld}`)
        }

        const baseText = baseExists ? await baseFile.text() : ''
        const updated = applyUnifiedDiff(baseText, patchText)

        await mkdir(path.dirname(resolvedNew), { recursive: true })
        await Bun.write(resolvedNew, updated)

        const isRename = Boolean(resolvedOld && resolvedOld !== resolvedNew)
        const relativeResolvedNew = relativeWorkspacePath(resolvedNew)
        const toPosix = (value: string) => value.split(path.sep).join('/')

        if (isRename && resolvedOld) {
          const existingOld = Bun.file(resolvedOld)
          if (await existingOld.exists()) {
            await unlink(resolvedOld)
          }
        }

        if (isRename && relativeOld) {
          results.push(`Moved ${toPosix(relativeOld)} -> ${toPosix(relativeResolvedNew)} via patch.`)
        } else if (baseExists) {
          results.push(`Updated ${relativeResolvedNew} via patch.`)
        } else {
          results.push(`Created ${relativeResolvedNew} via patch.`)
        }
      }

      return results.length === 1 ? (results[0] ?? '') : results.join('\n')
    },
    getPermissionRequest: ({ path: targetPath }) => ({
      subject: `Apply patch${targetPath ? `: ${targetPath}` : ''}`,
      metadata: { path: targetPath ?? null },
    }),
  }

  const executeShellTool: ToolDefinition<typeof executeShellSchema, string> = {
    id: 'executeShell',
    displayName: 'Execute Shell',
    description: 'Execute a shell command from the workspace root.',
    inputSchema: executeShellSchema,
    summarize: (result, context) =>
      formatToolSummary(
        summarizeToolCompletion('executeShell', context.input, result, { artifactPath: context.artifactPath }),
      ),
    execute: async ({ command, timeoutMs }, context) => {
      if (typeof command !== 'string') {
        throw new Error('Parameter "command" must be a string.')
      }

      const trimmedCommand = command.trim()
      if (!trimmedCommand) {
        return 'No command provided.'
      }

      if (context.shellTaskRunner) {
        const result = await context.shellTaskRunner.run(trimmedCommand, { background: false, timeoutMs })
        return result.formattedOutput
      }

      const result = await runShell(trimmedCommand)
      return formatShellResult(result.exitCode ?? 0, result.stdout, result.stderr)
    },
    getPermissionRequest: ({ command }) => ({
      subject: `Execute shell command: ${command}`,
      metadata: { command },
    }),
  }

  const slashCommandTool: ToolDefinition<typeof slashCommandSchema, SlashCommandExecution> = {
    id: 'slashCommand',
    displayName: 'Slash Command',
    description: slashCommandDescription,
    inputSchema: slashCommandSchema,
    execute: async ({ name, arguments: args }) => {
      return executeSlashCommand(name, args)
    },
    summarize: (result, context) =>
      formatToolSummary(
        summarizeToolCompletion('slashCommand', context.input, result, { artifactPath: context.artifactPath }),
      ),
  }

  const readTaskOutputTool: ToolDefinition<typeof readTaskOutputSchema, string> = {
    id: 'readTaskOutput',
    displayName: 'Read Task Output',
    description: 'Read persisted output for a runtime task.',
    inputSchema: readTaskOutputSchema,
    summarize: (result, context) =>
      formatToolSummary(
        summarizeToolCompletion('readTaskOutput', context.input, result, { artifactPath: context.artifactPath }),
      ),
    execute: async ({ taskId }) => {
      return readTaskOutput(taskId)
    },
  }

  const listTasksTool: ToolDefinition<typeof listTasksSchema, Record<string, unknown>[]> = {
    id: 'listTasks',
    displayName: 'List Tasks',
    description: 'List runtime shell and agent tasks with status summaries.',
    inputSchema: listTasksSchema,
    summarize: (result, context) =>
      formatToolSummary(
        summarizeToolCompletion('listTasks', context.input, result, { artifactPath: context.artifactPath }),
      ),
    execute: async (_input, context) => {
      const tasks = context.taskRuntime?.getSnapshot().tasks ?? []
      return tasks.map(summarizeTask)
    },
  }

  const getTaskStatusTool: ToolDefinition<typeof getTaskStatusSchema, Record<string, unknown> | string> = {
    id: 'getTaskStatus',
    displayName: 'Get Task Status',
    description: 'Read status metadata for a runtime task.',
    inputSchema: getTaskStatusSchema,
    summarize: (result, context) =>
      formatToolSummary(
        summarizeToolCompletion('getTaskStatus', context.input, result, { artifactPath: context.artifactPath }),
      ),
    execute: async ({ taskId }, context) => {
      const task = await context.taskRuntime?.getTask(taskId)
      return task ? summarizeTask(task) : `Task not found: ${taskId}`
    },
  }

  const waitForTasksTool: ToolDefinition<typeof waitForTasksSchema, Record<string, unknown>[]> = {
    id: 'waitForTasks',
    displayName: 'Wait For Tasks',
    description:
      'Wait until runtime shell or agent tasks finish. Use this instead of sleeping and repeatedly checking task status.',
    inputSchema: waitForTasksSchema,
    summarize: (result, context) =>
      formatToolSummary(
        summarizeToolCompletion('waitForTasks', context.input, result, { artifactPath: context.artifactPath }),
      ),
    execute: async ({ taskIds, timeoutMs }, context) => {
      if (!context.taskRuntime) {
        throw new Error('Task runtime is not configured.')
      }
      const tasks = await context.taskRuntime.waitForTasks(taskIds, {
        signal: context.signal,
        timeoutMs,
      })
      return tasks.map(summarizeTask)
    },
  }

  const cancelTaskTool: ToolDefinition<typeof cancelTaskSchema, Record<string, unknown> | string> = {
    id: 'cancelTask',
    displayName: 'Cancel Task',
    description: 'Cancel a pending or running runtime task.',
    inputSchema: cancelTaskSchema,
    summarize: (result, context) =>
      formatToolSummary(
        summarizeToolCompletion('cancelTask', context.input, result, { artifactPath: context.artifactPath }),
      ),
    execute: async ({ taskId }, context) => {
      if (!context.taskRuntime) {
        throw new Error('Task runtime is not configured.')
      }
      const task = await context.taskRuntime.cancelTask(taskId)
      return task ? summarizeTask(task) : `Task not found: ${taskId}`
    },
    getPermissionRequest: ({ taskId }) => ({
      subject: `Cancel task: ${taskId}`,
      metadata: { taskId },
    }),
  }

  const writeMemoryTool: ToolDefinition<typeof writeMemorySchema, string> = {
    id: 'writeMemory',
    displayName: 'Write Memory',
    description: 'Write a typed memory record to `.gambit/memory/`.',
    inputSchema: writeMemorySchema,
    summarize: (result, context) =>
      formatToolSummary(
        summarizeToolCompletion('writeMemory', context.input, result, { artifactPath: context.artifactPath }),
      ),
    execute: async ({ type, name, description, content }, context) => {
      if (!context.memoryStore) {
        throw new Error('Memory store is not configured.')
      }

      const record = await context.memoryStore.upsert({
        type,
        name,
        description,
        content,
      })
      return `Saved memory ${record.name} (${record.type}).`
    },
    getPermissionRequest: ({ name, type }) => ({
      subject: `Write ${type} memory: ${name}`,
      metadata: { name, type },
    }),
  }

  const tools: ToolDefinition<any, any>[] = [
    readFileTool,
    searchFilesTool,
    writeFileTool,
    patchFileTool,
    executeShellTool,
    slashCommandTool,
    readTaskOutputTool,
    listTasksTool,
    getTaskStatusTool,
    waitForTasksTool,
    cancelTaskTool,
    writeMemoryTool,
    enterPlanModeTool,
    exitPlanModeTool,
    askUserQuestionTool,
  ]

  if (cachedSkills.length > 0) {
    const activateSkillTool: ToolDefinition<typeof activateSkillSchema, string> = {
      id: 'activateSkill',
      displayName: 'Activate Skill',
      description: buildActivateSkillToolDescription(cachedSkills),
      inputSchema: activateSkillSchema,
      execute: async ({ name }) => {
        const activation = await activateSkill(name)
        return activation.content
      },
      summarize: (result, context) =>
        formatToolSummary(
          summarizeToolCompletion('activateSkill', context.input, result, { artifactPath: context.artifactPath }),
        ),
    }
    tools.push(activateSkillTool as ToolDefinition<any, any>)
  }

  if (options.includeMCPTools !== false) {
    tools.push(...(mcpManagementTools as ToolDefinition<any, any>[]))

    if (options.discoverMCPServerTools) {
      try {
        const discovered = await discoverMCPTools()
        tools.push(...(discovered as ToolDefinition<any, any>[]))
      } catch (error) {
        console.warn('Failed to discover MCP tools:', error)
      }
    }
  }

  if (options.includeSpawnAgent !== false) {
    const runAgentsTool: ToolDefinition<typeof runAgentsSchema, string> = {
      id: 'runAgents',
      displayName: 'Run Agents',
      description:
        'Run multiple delegated agents concurrently and wait for all results. Use this for parallel research or implementation when every result is needed before continuing.',
      inputSchema: runAgentsSchema,
      summarize: (result, context) =>
        formatToolSummary(
          summarizeToolCompletion('runAgents', context.input, result, { artifactPath: context.artifactPath }),
        ),
      execute: async ({ agents }, context) => {
        if (!context.agentTaskRunner || !context.agentExecutionOptions) {
          throw new Error('Agent task runner is not configured.')
        }
        const currentDepth = context.agentExecutionOptions.delegationDepth ?? 0
        const maxDepth = context.agentExecutionOptions.maxDelegationDepth ?? 3
        if (currentDepth >= maxDepth) {
          throw new Error(`Maximum delegation depth reached (${maxDepth}).`)
        }

        const result = await context.agentTaskRunner.runBatch({
          agents: agents.map((agent) => ({
            role: agent.role,
            prompt: agent.prompt,
            title: agent.description ?? `Delegated ${agent.role} agent`,
          })),
          apiKey: context.agentExecutionOptions.apiKey,
          modelId: context.agentExecutionOptions.modelId,
          reasoningEffort: context.agentExecutionOptions.reasoningEffort,
          baseSystemPrompt: context.agentExecutionOptions.baseSystemPrompt,
          agentExecutionOptions: {
            ...context.agentExecutionOptions,
            delegationDepth: currentDepth + 1,
            maxDelegationDepth: maxDepth,
          },
          signal: context.signal,
        })

        return formatAgentBatchResult(result)
      },
      getPermissionRequest: ({ agents }) => ({
        subject: `Run ${agents.length} delegated agent${agents.length === 1 ? '' : 's'} concurrently`,
        metadata: { agents: agents.map(({ role, description }) => ({ role, description })) },
      }),
    }

    const spawnAgentTool: ToolDefinition<typeof spawnAgentSchema, string> = {
      id: 'spawnAgent',
      displayName: 'Spawn Agent',
      description: 'Spawn a local delegated agent task.',
      inputSchema: spawnAgentSchema,
      summarize: (result, context) =>
        formatToolSummary(
          summarizeToolCompletion('spawnAgent', context.input, result, { artifactPath: context.artifactPath }),
        ),
      execute: async ({ role, prompt, description, background }, context) => {
        if (!context.agentTaskRunner || !context.agentExecutionOptions) {
          throw new Error('Agent task runner is not configured.')
        }
        const currentDepth = context.agentExecutionOptions.delegationDepth ?? 0
        const maxDepth = context.agentExecutionOptions.maxDelegationDepth ?? 3
        if (currentDepth >= maxDepth) {
          throw new Error(`Maximum delegation depth reached (${maxDepth}).`)
        }

        const result = await context.agentTaskRunner.run({
          role,
          prompt,
          title: description ?? `Delegated ${role} agent`,
          background: background ?? false,
          apiKey: context.agentExecutionOptions.apiKey,
          modelId: context.agentExecutionOptions.modelId,
          reasoningEffort: context.agentExecutionOptions.reasoningEffort,
          baseSystemPrompt: context.agentExecutionOptions.baseSystemPrompt,
          agentExecutionOptions: {
            ...context.agentExecutionOptions,
            delegationDepth: currentDepth + 1,
            maxDelegationDepth: maxDepth,
          },
          signal: context.signal,
        })

        if (!result.output) {
          return `Spawned ${role} agent task ${result.task.id}.`
        }

        return `Spawned ${role} agent task ${result.task.id}.\n\n${result.output}`
      },
      getPermissionRequest: ({ role, description }) => ({
        subject: `Spawn ${role} agent${description ? `: ${description}` : ''}`,
        metadata: { role, description },
      }),
    }

    tools.push(runAgentsTool)
    tools.push(spawnAgentTool)
  }

  return tools
}

export { formatShellResult, formatSlashCommandMessage, runShell }
